import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Samantha Durrant | Front End Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          property="og:title"
          content="Samantha Durrant | Front End Engineer"
        />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/digedcdik/image/upload/v1679615430/portfolio_gjidtg.pnghttps://res.cloudinary.com/digedcdik/image/upload/v1679615430/portfolio_gjidtg.png"
        />
        <meta
          property="og:description"
          content="Hey there! I'm Sam, a front end developer and designer who's always up
        for a challenge and loves collaborating with like-minded individuals who
        share my passion for growth."
        />
        <meta property="og:url" content="https://www.samanthadurrant.com/" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="heading2">
          I love learning and creating. Being a web developer means I get to do
          the things I love.
        </h2>
      </main>
    </>
  )
}
